name: Tests

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  tests:

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        framework: [net8.0]
        include:
          - sln: DummyMCP.sln

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ${{ matrix.sln }}
    - name: Build with dotnet
      run: dotnet build ${{ matrix.sln }} --configuration Release --no-restore
    - name: Run unit tests
      run: dotnet test ${{ matrix.sln }} --configuration Release --no-build --verbosity normal -f ${{ matrix.framework }}
